[package]
name = "asyncplay"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.96"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
